[default]
QUANTITY_ALLOWED_IN_QUEUE = 40
VERSION = 'SUPER05'
LIST_OF_TASKS = ['2020;SE-23-X-A;fClassS2',
 '2020;SE-23-V-B;fClassS2',
 '2020;SE-23-V-D;fClassS2',
 '2020;SE-23-X-C;fClassS2',
 '2020;SD-23-Z-C;fClassS2',
 '2020;SD-23-Z-A;fClassS2',
 '2020;SD-23-Z-D;fClassS2',
 '2020;SE-24-V-A;fClassS2',
 '2020;SD-24-Y-C;fClassS2',
 '2020;SD-23-Z-B;fClassS2',
 '2020;SD-24-Y-A;fClassS2',
 '2020;SD-23-X-D;fClassS2',
 '2020;SC-23-Y-D;fClassS2',
 '2020;SC-23-Z-C;fClassS2',
 '2020;SD-23-X-A;fClassS2',
 '2020;SD-23-V-B;fClassS2',
 '2020;SD-23-V-D;fClassS2',
 '2020;SD-23-X-C;fClassS2',
 '2020;SD-23-Y-B;fClassS2',
 '2020;SD-23-Y-D;fClassS2',
 '2020;SF-23-V-C;fClassS2',
 '2020;SF-23-V-A;fClassS2',
 '2020;SE-23-Y-C;fClassS2',
 '2020;SE-23-Y-A;fClassS2',
 '2020;SF-22-X-B;fClassS2',
 '2020;SE-22-Z-D;fClassS2',
 '2020;SE-22-Z-B;fClassS2',
 '2020;SE-22-Y-D;fClassS2',
 '2020;SF-21-Z-C;fClassS2',
 '2020;SF-23-Y-C;fClassS2',
 '2020;SG-22-X-B;fClassS2',
 '2020;SG-22-X-A;fClassS2',
 '2020;SF-22-Z-D;fClassS2',
 '2020;SF-22-Z-B;fClassS2',
 '2020;SF-22-X-D;fClassS2',
 '2020;SF-23-Y-A;fClassS2',
 '2020;SD-21-V-A;fClassS2',
 '2020;SD-20-X-B;fClassS2',
 '2020;SC-21-Y-C;fClassS2',
 '2020;SC-21-Y-D;fClassS2',
 '2020;SD-21-V-B;fClassS2',
 '2020;SD-21-X-A;fClassS2',
 '2020;SD-21-Z-C;fClassS2',
 '2020;SD-21-Z-A;fClassS2',
 '2020;SF-21-V-D;fClassS2',
 '2020;SF-21-Y-B;fClassS2',
 '2020;SF-21-X-D;fClassS2',
 '2020;SF-21-X-C;fClassS2',
 '2020;SF-21-Z-B;fClassS2',
 '2020;SF-21-Z-A;fClassS2',
 '2020;SG-21-X-B;fClassS2',
 '2020;SD-21-V-C;fClassS2',
 '2020;SF-22-Y-A;fClassS2',
 '2020;SF-22-V-C;fClassS2',
 '2020;SF-22-V-A;fClassS2',
 '2020;SE-22-Y-C;fClassS2',
 '2020;SE-21-Z-D;fClassS2',
 '2020;SF-21-X-B;fClassS2',
 '2020;SF-21-X-A;fClassS2',
 '2020;SF-21-V-B;fClassS2',
 '2020;SE-22-Z-A;fClassS2',
 '2020;SE-22-Z-C;fClassS2',
 '2020;SF-22-X-A;fClassS2',
 '2020;SF-22-Z-C;fClassS2',
 '2020;SF-22-Z-A;fClassS2',
 '2020;SF-22-Y-B;fClassS2',
 '2020;SF-22-V-B;fClassS2',
 '2020;SF-22-V-D;fClassS2',
 '2020;SE-22-V-D;fClassS2',
 '2020;SE-22-X-C;fClassS2',
 '2020;SE-22-X-A;fClassS2',
 '2020;SE-22-X-D;fClassS2',
 '2020;SE-22-X-B;fClassS2',
 '2020;SE-23-V-C;fClassS2',
 '2020;SE-23-V-A;fClassS2',
 '2020;SD-23-Y-C;fClassS2',
 '2020;SD-22-Y-B;fClassS2',
 '2020;SD-22-Y-C;fClassS2',
 '2020;SD-22-Y-D;fClassS2',
 '2020;SE-22-V-A;fClassS2',
 '2020;SE-22-V-C;fClassS2',
 '2020;SE-22-Y-A;fClassS2',
 '2020;SE-22-Y-B;fClassS2',
 '2020;SE-22-V-B;fClassS2',
 '2020;SE-21-X-A;fClassS2',
 '2020;SE-21-Z-C;fClassS2',
 '2020;SE-21-Z-B;fClassS2',
 '2020;SE-21-X-D;fClassS2',
 '2020;SD-21-Z-B;fClassS2',
 '2020;SD-21-Z-D;fClassS2',
 '2020;SE-21-X-B;fClassS2',
 '2020;SD-22-Y-A;fClassS2',
 '2020;SD-21-X-C;fClassS2',
 '2020;SD-21-V-D;fClassS2',
 '2020;SD-21-Y-B;fClassS2',
 '2020;SD-21-Y-A;fClassS2',
 '2020;SD-21-Y-D;fClassS2',
 '2020;SD-21-Y-C;fClassS2',
 '2020;SE-21-Y-D;fClassS2',
 '2020;SE-21-V-B;fClassS2',
 '2020;SC-22-Y-B;fClassS2',
 '2020;SD-22-V-C;fClassS2',
 '2020;SD-21-X-D;fClassS2',
 '2020;SD-21-X-B;fClassS2',
 '2020;SC-22-X-A;fClassS2',
 '2020;SB-22-Z-C;fClassS2',
 '2020;SB-22-Z-B;fClassS2',
 '2020;SC-22-X-B;fClassS2',
 '2020;SC-22-X-D;fClassS2',
 '2020;SC-22-X-C;fClassS2',
 '2020;SC-22-Z-A;fClassS2',
 '2020;SD-22-X-A;fClassS2',
 '2020;SC-22-Z-C;fClassS2',
 '2020;SD-22-V-D;fClassS2',
 '2020;SD-22-V-B;fClassS2',
 '2020;SC-22-Y-D;fClassS2',
 '2020;SC-22-Z-D;fClassS2',
 '2020;SD-22-X-B;fClassS2',
 '2020;SD-23-V-A;fClassS2',
 '2020;SC-23-Y-C;fClassS2',
 '2020;SC-23-V-A;fClassS2',
 '2020;SC-23-Y-A;fClassS2',
 '2020;SC-23-V-C;fClassS2',
 '2020;SC-22-Z-B;fClassS2',
 '2020;SD-23-V-C;fClassS2',
 '2020;SD-23-Y-A;fClassS2',
 '2020;SD-22-Z-D;fClassS2',
 '2020;SD-22-Z-C;fClassS2',
 '2020;SD-22-Z-B;fClassS2',
 '2020;SD-22-Z-A;fClassS2',
 '2020;SD-22-X-D;fClassS2',
 '2020;SD-22-X-C;fClassS2',
 '2020;SC-23-V-B;fClassS2',
 '2020;SC-23-X-A;fClassS2',
 '2020;SB-23-Z-C;fClassS2',
 '2020;SB-23-Z-D;fClassS2',
 '2020;SC-23-V-D;fClassS2',
 '2020;SC-23-X-C;fClassS2',
 '2020;SC-23-Y-B;fClassS2',
 '2020;SC-23-Z-A;fClassS2',
 '2020;SB-23-X-A;fClassS2',
 '2020;SB-23-V-D;fClassS2',
 '2020;SB-23-X-C;fClassS2',
 '2020;SB-23-X-D;fClassS2',
 '2020;SB-23-Z-B;fClassS2',
 '2020;SB-23-Z-A;fClassS2',
 '2020;SB-23-Y-B;fClassS2',
 '2020;SB-23-Y-D;fClassS2',
 '2020;SB-24-Y-A;fClassS2',
 '2020;SA-24-Y-C;fClassS2',
 '2020;SB-24-V-A;fClassS2',
 '2020;SB-24-V-C;fClassS2',
 '2020;SA-23-Z-D;fClassS2',
 '2020;SB-23-X-B;fClassS2',
 '2020;SA-23-Z-C;fClassS2',
 '2020;SB-23-V-B;fClassS2',
 '2020;SB-22-Z-D;fClassS2',
 '2020;SB-23-Y-C;fClassS2',
 '2020;SB-23-Y-A;fClassS2',
 '2020;SB-23-V-C;fClassS2',
 '2020;SB-22-X-D;fClassS2',
 '2020;SA-23-Z-A;fClassS2',
 '2020;SA-23-Z-B;fClassS2',
 '2020;SA-24-Y-A;fClassS2',
 '2020;SE-23-Y-B;fClassS2',
 '2020;SE-23-Z-A;fClassS2',
 '2020;SE-23-Z-D;fClassS2',
 '2020;SE-23-Z-C;fClassS2',
 '2020;SE-23-Y-D;fClassS2',
 '2020;SF-23-V-B;fClassS2',
 '2020;SF-23-X-A;fClassS2',
 '2020;SF-23-V-D;fClassS2',
 '2020;SD-23-X-B;fClassS2',
 '2020;SE-23-X-B;fClassS2',
 '2020;SE-23-Z-B;fClassS2',
 '2020;SE-23-X-D;fClassS2']



PRIVATEKEY = '.lapig_api/privatekey.json'
IS_LOGIN_MANUAL = false

DB = 'task_lapig'
DB_HOST = 'localhost'
DB_PORT = 27017





SERVER = "flaskdynaconf.com"
PORT = 6666
MESSAGE = "Dynaconf works like a charm with Flask and TOML"
TEST_RULE='/flask_with_toml'

[development]
DEBUG = true
SERVER = "localhost"
PORT = 5000

[production]
DEBUG = false
SERVER = "prod.flaskdynaconf.com"
